INCLUDES = -I../include
CC = sdcc -mmcs51
BASENAME = bench_dump
BENCHAPP = benchap

$(BASENAME).ihx: $(BASENAME).c
	$(CC) $(INCLUDES) $(BASENAME).c

clean:
	rm -f $(BASENAME).{asm,ihx,lnk,lst,map,mem,rel,rst,sym,lk,omf,cdb,dat}

.PHONY:run
run: $(BASENAME).ihx
	$(BENCHAPP) prg:$(BASENAME).ihx run delay:10 reset dram:0,16384

.PHONY:
fifo_clear: $(BASENAME2).ihx
	$(BENCHAPP) prg:$(BASENAME2).ihx run delay:300

